language: node_js
node_js:
  - '6'
  - '4'
script:
  - npm run coverage
after_script:
  - 'npm install codeclimate-test-reporter && cat coverage/lcov.info | codeclimate'
env:
  global:
    - secure: SqgCU5ugyYmoyCd5jyaoWDw3bWtl9bvbretQMmQRQtRVdzVR/2tOaf19D2vMoDFcNZCPIklmjHPldxpF6sQ/1OVM3ZyNQXu9WUUMuQE/VGSzNPYUFnXeH2gdBOKY2O2Cwptsb2Xm2BRD0nPaMC57X/obE6O/Pm9U827mEWvnsqo=
