name: Node.js CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    
    runs-on: ubunutu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x, 15.x]
    
   - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn install --immutable --immutable-cache --check-cache
      - run: yarn test